//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChiTieu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuNhap
    {
        public int ID { get; set; }
        public string DanhMuc { get; set; }
        public decimal SoTien { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
